#+title: Movies 🎥
#+author: Troy Fischer
#+setupfile: ./themes/org/troy-story.setup
#+include: ./header.org

Movies I'm watching...

* Don't Worry Darling
Surprised by the negative ratings on this one. Sure some things don't make sense
(why would you program the guys to die in real life??) and the concept might be
a bit played out at this point but I enjoyed it.
* Amsterdam
Cool actors but felt like a flop.
* Matilda
How dare they portray the average American family so accurately.
* The Menu
Class struggle movie except between members of the working class. Transitions reminded me of Everything Everywhere All At Once.
* Avatar 2
Avatars live in a lovely communist utopia
* 2001 A Space Odyssey
Needed some additonal help from Reddit to understand the story.
* No Country For Old Men
The ending is a change of pace from most movies that have a clearer conflict/resolution style ending.
* Taxi Driver
Not my favorite but interesting enough to watch the entire thing.
* Get Out
Wow it was good.
* Ex Machina
Do I even pass the Turing the test?
* Whiplash
Drum solos
* Parasite
Cool movie about the struggle of working class people while the wealthy are completely oblivious.
* Everything Everywhere All At Once
It's all pointless but please be nice.
* Avatar
* Juno
* BlacKKKlansman
* Black Panther
* Blue Velvet
* Don’t Worry Darling
* Eraserhead
* Citizen Kane
* Momento
* Zone of Interest
* White Girls
* Inception
* How to lose a guy in 10 days
snoozer
* The fall guy
